version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: src/app/api/Dockerfile
    container_name: fastapi_api
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://api:8000/predictions
      - GCP_PROJECT_ID=tri-demandes-clients
      - GCS_BUCKET_NAME=clean_complaints
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/tri-demandes-clients-da1709669c29.json
    volumes:
      - ./secrets/tri-demandes-clients-da1709669c29.json:/secrets/tri-demandes-clients-da1709669c29.json:ro

  streamlit:
    build:
      context: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/predictions
      - GCP_PROJECT_ID=tri-demandes-clients
      - GCS_BUCKET_NAME=clean_complaints
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/tri-demandes-clients-da1709669c29.json
    volumes:
      - ./secrets/tri-demandes-clients-da1709669c29.json:/secrets/tri-demandes-clients-da1709669c29.json:ro

